{% set name = "rcx-tk" %}
{% set version = "0.1.0" %}

package:
  name: rcx-tk
  version: {{ version }}

source:
  url:https://files.pythonhosted.org/packages/65/bd/287c60a98c7e05b2c6edaa0549ce6f83ab0e2c89e9e482901cb283ae9856/rcx_tk-{{ version }}.tar.gz
  sha256: 78eb18c1b90289b9e39d2451cb444ded39134fa9e56744cf692839e7835ddb04

build:
  entry_points:
    - rcx_tk = rcx_tk.__main__:main
  run_exports:
    - {{ pin_subpackage("rcx-tk", max_pin="x.x") }}
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.11.0,<4.0.0
    - pandas >=2.2.2,<3.0.0
    - openpyxl >=1.1.3,<2.0.0
    - pandas-stubs >=2.2.2,<3.0.0
    - mypy >=1.10.1,<2.0.0
    - click >=8.1.7,<9.0.0

test:
  imports:
    - rcx_tk
  commands:
    - pip check
    - rcx_tk --help
  requires:
    - pip

about:
  home: https://github.com/RECETOX/rcx-tk
  summary: This package adjusts and cleans the metadata file provided by a user.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - KristinaGomoryova
